const products = [
    {
      id: 0,
      name: "Koszulka1",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "T-shirts",
      price: 99.99,
      image: "./images/1zdjwww.jpg",
      sale: true,
      saleAmount: 40,
    },
    {
      id: 1,
      name: "Dziksons1",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "T-shirts",
      price: 99.99,
      image: "./images/2zdjwww.jpg",
    },
    {
      id: 2,
      name: "Dziksons2",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "T-shirts",
      price: 299.99,
      image: "./images/3zdjwww.jpg",
      sale: true,
      saleAmount: 100,
    },
    {
      id: 3,
      name: "Air Force 1",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "Fancy shoes",
      price: 499.99,
      image: "./images/4zdjwww.jpg",
    },
    {
      id: 4,
      name: "Air Max 1",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "Fancy shoes",
      price: 599.99,
      image: "./images/6zdjwww.jpg",
    },
    {
      id: 5,
      name: "Nike Superfly 9",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "Football equipment",
      price: 1099.99,
      image: "./images/7zdjwww.jpg",
      sale: true,
      saleAmount: 250,
    },
    {
      id: 6,
      name: "Madrid Away Shirt",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "Football equipment",
      price: 399.99,
      image: "./images/8zdjwww.jpg",
    },
    {
      id: 7,
      name: "Copa del Ray",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "Soccer balls",
      price: 449.99,
      image: "./images/9zdjwww.jpg",
    },
    {
      id: 8,
      name: "UCL 1",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "Soccer balls",
      price: 499.99,
      image: "./images/10zdjwww.jpg",
      sale: true,
      saleAmount: 300,
    },
    {
      id: 9,
      name: "Youth 2023",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "Soccer balls",
      price: 299.99,
      image: "./images/11zdjwww.jpg",
    },
  ];